### PR TITLE
Examples for accessing the GPU via Docker

### PR DESCRIPTION
**Pull request by sameerd**
Hi, 

Here are a few examples for accessing the GPU via Docker. There are two 'fake' examples and one 'real' example. 

1. **Hello_GPU** Just a one line execute file to see if we can talk to the GPU
2. **tensorflow_python** Matrix multiplication on the GPU vs CPU. This is copied and modified from [StackOverflow](https://stackoverflow.com/questions/41804380/testing-gpu-with-tensorflow-matrix-multiplication).
3. **pytorch_python** This is a 'real' example with sample data that runs a convolutional neural network to classify the MNIST digits dataset.  This example is taken from the [Official Pytorch examples](https://github.com/pytorch/examples/blob/master/mnist/main.py) and then modified. The datafile is 33MB in size and is included with this PR. 

Please feel free to change or modify anything and keep only what you need. 

Rgds

### CODE REVIEW

**Comment by agitter** [comment]
Thanks for all the contributions @sameerd!  These examples were high on our internal priority list.

This repository is so new that we don't have a pull request review procedure in place.  I wanted to let you know that one of us will give feedback so we can work on merging this.

**Comment by sameerd** [comment]
You are welcome @agitter!  

Lauren requested some examples after she helped me get this running last week. I sent her a message and I assume she will review the PR some point.

**Comment by lmichael107** [comment]
Yes, thank you, Sameer!

We'll review you contributions soon. Even if there are formatting changes
(we haven't decided yet on what might be best), we'll probably merge and
then work, ourselves, at any tweaks, but we'll let you know if we have any
questions or change requests that you'd be best to address.

**Comment by lmichael107** [comment]
Tony, thank you for the review. I've got another CHTC team member (@iross) who will run through everything and provide input

Regarding your points:
1. What license would you suggest? I'm most familiar with what Software Carpentry uses (Creative Commons: https://github.com/swcarpentry/shell-novice/blob/gh-pages/LICENSE.md), but am also familiar with the basics of Gnu and MIT (https://choosealicense.com/).
2. Sounds like a good use of the Readme for each example. @sameerd, do have any requests from us in terms of how we attribute the initial materials to you, and opinions as a contributor relevant to licensing? (It's okay if not.)
3. I also like the idea of having output, in a different folder, even with the additional maintenance.

**Comment by sameerd** [comment]
Lauren, I don't have any requests re attribution. However with licensing the more permissive for users the better. Software Carpentry has a pretty good license with documentation licensed under creative commons and code under the MIT license. 

Anyway I updated the two examples I copied from the internet with their own licenses and added two more commits.

**Comment by iross** [comment]
Looks good to me! Thanks for putting this together. Everything is clear and works out of the box on CHTC.

re: example output, I think that it works well as it currently is. I expect that these examples will be fairly stable, so the overheads (both maintenance and data sizes) are pretty minimal.

**Comment by lmichael107** [comment]
Agreed. I think we can state that example data needs to be sufficiently small to not over-burden the repo (or users of it) or require data availability tools outside of regular HTCondor file transfer, OR that examples use data that is publicly available (downloadable, perhaps on CHTC's 'squid' web server) to the job.

**Comment by lmichael107** [comment]
Regarding licensing, let's go with Creative Commons? Sameer, do you want to review the Readme files you created, and attribute to yourself with something like "Materials for this example were initially developed and contributed by <Your Name> (<your GitHub user page>)."  ?

**Comment by sameerd** [comment]
Lauren, if you don't mind I don't particularly want to put my name on these examples. It didn't take much time to develop. The Github pull request and commit record is enough of attribution for me.

**Comment by lmichael107** [comment]
I think that's fine by us. Tony, shall we merge?

Lauren

**Pull request merged**
