### PR TITLE
requirement_updates

### PR DESCRIPTION
**Pull request by PatStiles**

### CODE REVIEW

**Review by agitter — COMMENTED** [review]
Thanks @PatStiles. Can you please check the readmes as well? Some of them reference these attributes as well.

@ChristinaLK please let us know when we can test that these updated examples still run in CHTC.

**Review by ChristinaLK — COMMENTED** [review]
So the real change is that instead of using `requirements`, the submit file will now use `require_gpus`. 

So`requirements = GPUs_Capability < 8.0` becomes `require_gpus = Capability < 8.0`. That's the second part of the change, beyond the name of the attribute.

**Comment by agitter** [comment]
> We may want to merge as a non-master branch so it's easier to clone and test them before switching over.

Good point.  I'll attempt to follow https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by PatStiles** [comment]
sounds good guys!

**Pull request closed without merging**
